# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import open_ai_pb2 as open__ai__pb2


class OpenAIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskChatGPT = channel.unary_unary(
                '/OpenAI/AskChatGPT',
                request_serializer=open__ai__pb2.AskChatGPTRequest.SerializeToString,
                response_deserializer=open__ai__pb2.AskChatGPTResponse.FromString,
                )


class OpenAIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AskChatGPT(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenAIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskChatGPT': grpc.unary_unary_rpc_method_handler(
                    servicer.AskChatGPT,
                    request_deserializer=open__ai__pb2.AskChatGPTRequest.FromString,
                    response_serializer=open__ai__pb2.AskChatGPTResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OpenAI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OpenAI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AskChatGPT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OpenAI/AskChatGPT',
            open__ai__pb2.AskChatGPTRequest.SerializeToString,
            open__ai__pb2.AskChatGPTResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
