# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: open_ai.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ropen_ai.proto\"\x13\n\x11\x41skChatGPTRequest\"\x14\n\x12\x41skChatGPTResponse2A\n\x06OpenAI\x12\x37\n\nAskChatGPT\x12\x12.AskChatGPTRequest\x1a\x13.AskChatGPTResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'open_ai_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ASKCHATGPTREQUEST._serialized_start=17
  _ASKCHATGPTREQUEST._serialized_end=36
  _ASKCHATGPTRESPONSE._serialized_start=38
  _ASKCHATGPTRESPONSE._serialized_end=58
  _OPENAI._serialized_start=60
  _OPENAI._serialized_end=125
# @@protoc_insertion_point(module_scope)
